services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root # Needed to access docker socket
    ports:
      - "8080:8080"
      - "50000:50000" # Agent connection port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Give Jenkins access to Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_home:
